env:
  browser: true
  es2021: true
extends:
- eslint:recommended
- plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
- '@typescript-eslint'
rules:
  "@typescript-eslint/no-unused-vars": [error, {destructuredArrayIgnorePattern: ^_}]
  accessor-pairs: error
  array-bracket-spacing: error
  arrow-spacing: error
  block-spacing: [error, always]
  brace-style: error
  class-methods-use-this: warn
  comma-dangle: [error, always-multiline]
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  consistent-return: error
  default-case-last: error
  default-param-last: error
  dot-location: [error, property]
  eol-last: [error, always]
  eqeqeq: [error, smart]
  function-call-argument-newline: [error, consistent]
  function-paren-newline: [error, consistent]
  generator-star-spacing: error
  implicit-arrow-linebreak: error
  indent: [error, 4]
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  line-comment-position: error
  linebreak-style: [error, unix]
  lines-around-comment: error
  max-len: [error, 120]
  max-statements-per-line: error
  multiline-ternary: error
  new-parens: error
  newline-per-chained-call: error
  no-alert: error
  no-array-constructor: error
  no-caller: error
  no-constructor-return: error
  no-duplicate-imports: error
  no-eval: error
  no-extra-parens: error
  no-multi-spaces: error
  no-multiple-empty-lines: error
  no-promise-executor-return: error
  no-tabs: error
  no-template-curly-in-string: error
  no-trailing-spaces: error
  no-unused-private-class-members: error
  no-use-before-define: error
  no-var: error
  no-whitespace-before-property: error
  nonblock-statement-body-position: error
  object-curly-newline: error
  object-curly-spacing: [error, always]
  object-property-newline: error
  operator-linebreak: error
  padded-blocks: [error, never]
  padding-line-between-statements: error
  prefer-const: error
  quotes: [error, double]
  rest-spread-spacing: error
  semi-spacing: error
  semi-style: error
  semi: [error, never]
  space-before-blocks: error
  space-before-function-paren: [error, never]
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  switch-colon-spacing: error
  template-curly-spacing: error
  template-tag-spacing: error
  unicode-bom: error
  wrap-iife: error
  wrap-regex: error
  yield-star-spacing: error
