name: Lint
runs:
  using: composite
  steps:
  - shell: bash
    run: ./gradlew lint
  - uses: yutailang0119/action-android-lint@v3
    if: always()
    with:
      report-path: '**/build/reports/*.xml'
