name: Import Certificate
inputs:
  certificate:
    description: 'The certificate in p12 format, encoded as base64'
    required: true
  password:
    description: 'The certificate password'
    required: true
runs:
  using: composite
  steps:
  - shell: bash
    run: |
      security list-keychains -d user -s login.keychain Developer.keychain

      if [[ ! -f "$HOME/Library/Keychains/Developer.keychain-db" ]]; then
        security create-keychain -p "${{ inputs.password }}" Developer.keychain
        security set-keychain-settings -lut 21600 Developer.keychain

        for CERT_INDEX in {2..8}; do
          CERT_FILE=AppleWWDRCAG${CERT_INDEX}.cer
          curl --proto '=https' --tlsv1.2 -sSOf "https://www.apple.com/certificateauthority/$CERT_FILE"
          security import $CERT_FILE -k Developer.keychain -f openssl
          rm $CERT_FILE
        done
      fi

      security unlock-keychain -p "${{ inputs.password }}" Developer.keychain

      echo -n "${{ inputs.certificate }}" | base64 -d > Developer.p12
      security import Developer.p12 \
        -k Developer.keychain \
        -f pkcs12 \
        -A \
        -T /usr/bin/codesign \
        -T /usr/bin/security \
        -P "${{ inputs.password }}"

      security set-key-partition-list -S apple-tool:,apple: -k "${{ inputs.password }}" Developer.keychain
