name: Docker Build
on:
  push:
    branches:    
    - main
jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build Image
      run: nix build .
    - name: Publish Image
      run: skopeo copy --dest-creds ${{ github.repository_owner }}:${{ secrets.PACKAGES_TOKEN }} docker-archive:result docker://ghcr.io/${{ github.repository_owner }}/wallet-dev:latest
