name: Android Build
on:
  push:
    branches:    
    - main
  pull_request:
    branches:
    - "*"
jobs:
  build:
    name: Build (Android)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        submodules: recursive
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
        cache: gradle
    - name: Build
      run: ./gradlew assembleDebug
    - name: Build Unit Tests
      run: ./gradlew assembleAndroidTest
    - name: Unit Test
      continue-on-error: true
      uses: ./.github/actions/gradle-test
      with:
        task: testDebugUnitTest
        check-name: Android Tests
