name: Apple Lint
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - "*"
jobs:
  lint:
    name: Swift Lint
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        submodules: recursive
    - name: Lint
      run: swiftlint lint --reporter github-actions-logging
