name: Apple Lint
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - "*"
jobs:
  lint:
    name: Swift Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
    - name: Lint
      run: swiftlint lint --reporter github-actions-logging
